-- Generated extraction_fields
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_00', 'ext_demo_ins', 'title', 'Property Insurance Policy — Pine Grove (2026 Renewal)', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_01', 'ext_demo_ins', 'counterparty_name', 'Chubb Insurance Company', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_02', 'ext_demo_ins', 'counterparty_email', 'service@chubb.com', 0.92);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_03', 'ext_demo_ins', 'smartland_entity', 'Smartland Realty LLC', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_04', 'ext_demo_ins', 'property_or_site', 'Pine Grove Apartments', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_05', 'ext_demo_ins', 'effective_date', '2026-06-01', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_06', 'ext_demo_ins', 'expiration_date', '2027-05-31', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_07', 'ext_demo_ins', 'auto_renewal', 'True', 0.94);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_08', 'ext_demo_ins', 'renewal_term', '1 year', 0.91);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_09', 'ext_demo_ins', 'notice_period_days', '30', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_10', 'ext_demo_ins', 'notice_deadline', '2027-05-01', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_11', 'ext_demo_ins', 'total_value_usd', '48500', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_12', 'ext_demo_ins', 'recurring_value_usd', '48500', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_13', 'ext_demo_ins', 'payment_terms', 'Annual premium', 0.9);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_14', 'ext_demo_ins', 'governing_law', 'Ohio', 0.82);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_15', 'ext_demo_ins', 'signed', 'True', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_16', 'ext_demo_ins', 'signature_dates', '2026-05-12', 0.84);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts17', 'ext_demo_ins', 'ts_carrier', 'Chubb Insurance Company', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts18', 'ext_demo_ins', 'ts_policy_number', 'PI-2026-44871', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts19', 'ext_demo_ins', 'ts_coverage_type', 'Property + General Liability', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts20', 'ext_demo_ins', 'ts_coverage_limit_per_occurrence', '5000000', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts21', 'ext_demo_ins', 'ts_coverage_limit_aggregate', '10000000', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts22', 'ext_demo_ins', 'ts_deductible', '25000', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts23', 'ext_demo_ins', 'ts_named_insured', 'Smartland Realty LLC', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts24', 'ext_demo_ins', 'ts_premium', '48500', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_ins_ts25', 'ext_demo_ins', 'ts_premium_schedule', 'Annual', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_00', 'ext_demo_msa', 'title', 'Master Services Agreement — Acme HVAC Services', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_01', 'ext_demo_msa', 'counterparty_name', 'Acme HVAC Services LLC', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_02', 'ext_demo_msa', 'smartland_entity', 'Smartland Realty LLC', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_03', 'ext_demo_msa', 'effective_date', '2024-08-15', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_04', 'ext_demo_msa', 'expiration_date', '2026-08-15', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_05', 'ext_demo_msa', 'auto_renewal', 'True', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_06', 'ext_demo_msa', 'renewal_term', '1 year', 0.94);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_07', 'ext_demo_msa', 'notice_period_days', '60', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_08', 'ext_demo_msa', 'notice_deadline', '2026-06-16', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_09', 'ext_demo_msa', 'total_value_usd', '240000', 0.84);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_10', 'ext_demo_msa', 'payment_terms', 'Net 30', 0.92);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_11', 'ext_demo_msa', 'governing_law', 'Ohio', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_ts12', 'ext_demo_msa', 'ts_scope_summary', 'HVAC maintenance and emergency repair services', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_msa_ts13', 'ext_demo_msa', 'ts_limitation_of_liability', 'Cap at fees paid in trailing 12 months', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_00', 'ext_demo_util', 'title', 'Cleveland Water Service Agreement — Pine Grove', 0.94);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_01', 'ext_demo_util', 'counterparty_name', 'Cleveland Division of Water', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_02', 'ext_demo_util', 'smartland_entity', 'Smartland Realty LLC', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_03', 'ext_demo_util', 'property_or_site', 'Pine Grove Apartments', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_04', 'ext_demo_util', 'effective_date', '2025-01-01', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_05', 'ext_demo_util', 'expiration_date', '2026-12-31', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_06', 'ext_demo_util', 'auto_renewal', 'True', 0.92);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_07', 'ext_demo_util', 'renewal_term', '1 year', 0.9);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_08', 'ext_demo_util', 'notice_period_days', '90', 0.93);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_09', 'ext_demo_util', 'notice_deadline', '2026-10-02', 0.9);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_10', 'ext_demo_util', 'total_value_usd', NULL, 0.5);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_11', 'ext_demo_util', 'governing_law', 'Ohio', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_ts12', 'ext_demo_util', 'ts_service_address', 'Pine Grove Apartments, Cleveland OH', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_ts13', 'ext_demo_util', 'ts_account_number', '8841-22193', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_ts14', 'ext_demo_util', 'ts_rate_structure', 'Tiered residential', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_util_ts15', 'ext_demo_util', 'ts_deposit_amount', '2500', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_00', 'ext_demo_gas', 'title', 'Dominion Energy Ohio — Hall of Fame Service', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_01', 'ext_demo_gas', 'counterparty_name', 'Dominion Energy Ohio', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_02', 'ext_demo_gas', 'smartland_entity', 'Smartland Realty LLC', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_03', 'ext_demo_gas', 'property_or_site', 'Hall of Fame Apartments', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_04', 'ext_demo_gas', 'effective_date', '2024-03-01', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_05', 'ext_demo_gas', 'expiration_date', '2027-02-28', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_06', 'ext_demo_gas', 'auto_renewal', 'True', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_07', 'ext_demo_gas', 'renewal_term', '1 year', 0.92);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_08', 'ext_demo_gas', 'notice_period_days', '90', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_09', 'ext_demo_gas', 'notice_deadline', '2026-11-30', 0.94);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_10', 'ext_demo_gas', 'governing_law', 'Ohio', 0.92);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_ts11', 'ext_demo_gas', 'ts_service_address', 'Hall of Fame Apartments, Canton OH', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_ts12', 'ext_demo_gas', 'ts_account_number', '7720-11338', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_gas_ts13', 'ext_demo_gas', 'ts_rate_structure', 'Commercial fixed', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_00', 'ext_demo_loan', 'title', 'PNC Bank — Pine Grove Acquisition Loan', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_01', 'ext_demo_loan', 'counterparty_name', 'PNC Bank, National Association', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_02', 'ext_demo_loan', 'smartland_entity', 'Smartland Realty LLC', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_03', 'ext_demo_loan', 'property_or_site', 'Pine Grove Apartments', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_04', 'ext_demo_loan', 'effective_date', '2024-09-30', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_05', 'ext_demo_loan', 'expiration_date', '2030-09-30', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_06', 'ext_demo_loan', 'auto_renewal', 'False', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_07', 'ext_demo_loan', 'total_value_usd', '14500000', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_08', 'ext_demo_loan', 'governing_law', 'Ohio', 0.93);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts09', 'ext_demo_loan', 'ts_lender', 'PNC Bank, N.A.', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts10', 'ext_demo_loan', 'ts_principal', '14500000', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts11', 'ext_demo_loan', 'ts_rate', '6.25% fixed', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts12', 'ext_demo_loan', 'ts_maturity', '2030-09-30', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts13', 'ext_demo_loan', 'ts_financial_covenants', 'DSCR >= 1.25x; LTV <= 70%', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_loan_ts14', 'ext_demo_loan', 'ts_reporting_cadence', 'Quarterly compliance certificates due 30 days after quarter end', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_00', 'ext_demo_legal', 'title', 'Engagement Letter — Kelley Drye & Warren', 0.94);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_01', 'ext_demo_legal', 'counterparty_name', 'Kelley Drye & Warren LLP', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_02', 'ext_demo_legal', 'smartland_entity', 'Smartland Holdings LLC', 0.93);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_03', 'ext_demo_legal', 'effective_date', '2025-04-01', 0.98);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_04', 'ext_demo_legal', 'expiration_date', NULL, 0.5);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_05', 'ext_demo_legal', 'auto_renewal', 'False', 0.9);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_06', 'ext_demo_legal', 'notice_period_days', '30', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_07', 'ext_demo_legal', 'governing_law', 'New York', 0.9);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_legal_ts08', 'ext_demo_legal', 'ts_scope_summary', 'Reg A+ filings & corporate governance for Smartland Energy LLC', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_00', 'ext_demo_equip', 'title', 'INNIO Jenbacher J920 — Equipment Purchase & Warranty', 0.96);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_01', 'ext_demo_equip', 'counterparty_name', 'INNIO Jenbacher GmbH', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_02', 'ext_demo_equip', 'smartland_entity', 'Smartland Energy LLC', 0.99);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_03', 'ext_demo_equip', 'property_or_site', 'Van Wert Site', 0.97);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_04', 'ext_demo_equip', 'effective_date', '2025-11-01', 0.93);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_05', 'ext_demo_equip', 'expiration_date', '2028-12-01', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_06', 'ext_demo_equip', 'auto_renewal', 'False', 0.95);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_07', 'ext_demo_equip', 'total_value_usd', NULL, 0.5);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_08', 'ext_demo_equip', 'governing_law', 'New York', 0.86);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts09', 'ext_demo_equip', 'ts_make_model', 'INNIO Jenbacher J920 FleXtra (9.5 MW)', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts10', 'ext_demo_equip', 'ts_serial_numbers', 'J920-NA-0042, J920-NA-0043', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts11', 'ext_demo_equip', 'ts_delivery_date', '2026-09-15', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts12', 'ext_demo_equip', 'ts_commissioning_date', '2026-12-01', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts13', 'ext_demo_equip', 'ts_warranty_start', '2026-12-01', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts14', 'ext_demo_equip', 'ts_warranty_length_months', '24', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts15', 'ext_demo_equip', 'ts_warranty_exclusions', 'Operator misuse, fuel out-of-spec', 0.85);
INSERT OR IGNORE INTO extraction_fields (id, extraction_id, field_name, field_value, confidence) VALUES ('ef_demo_equip_ts16', 'ext_demo_equip', 'ts_service_interval', 'Major service every 4,000 operating hours', 0.85);
